include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = HaiLockGlassClockPrefs

HaiLockGlassClockPrefs_FILES = HLGCRootListController.m
HaiLockGlassClockPrefs_CFLAGS = -fobjc-arc
HaiLockGlassClockPrefs_FRAMEWORKS = UIKit Foundation CoreFoundation
HaiLockGlassClockPrefs_INSTALL_PATH = /Library/PreferenceBundles

HaiLockGlassClockPrefs_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
