include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = HaiLockGlassClockPrefs

HaiLockGlassClockPrefs_FILES = HLGCRootListController.m
HaiLockGlassClockPrefs_CFLAGS = -fobjc-arc
HaiLockGlassClockPrefs_FRAMEWORKS = UIKit
HaiLockGlassClockPrefs_PRIVATE_FRAMEWORKS = Preferences
HaiLockGlassClockPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk
